### ISSUE TITLE
Jest Unit TEST coverage printing error 

### ISSUE THREAD

**Issue by Ralpis** [Ralpis/Na-Hak-Gong#3]
**Error Log** 

` at Object.<anonymous> (C:\Users\TY\Desktop\Practice_folder\Na-Hak-Gong\Na-Hak-Gong\src\users\user.service.spec.ts:99:49)
        at Object.asyncJestTest (C:\Users\TY\Desktop\Practice_folder\Na-Hak-Gong\Na-Hak-Gong\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
        at C:\Users\TY\Desktop\Practice_folder\Na-Hak-Gong\Na-Hak-Gong\node_modules\jest-jasmine2\build\queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (C:\Users\TY\Desktop\Practice_folder\Na-Hak-Gong\Na-Hak-Gong\node_modules\jest-jasmine2\build\queueRunner.js:28:19)       
        at C:\Users\TY\Desktop\Practice_folder\Na-Hak-Gong\Na-Hak-Gong\node_modules\jest-jasmine2\build\queueRunner.js:75:41`

How to fix...  T T

**Comment by Ralpis** [comment]
at UsersService.createAccount (users/users.service.ts:46:15)
console.log delete !
